### ISSUE TITLE
read

### ISSUE THREAD

**Issue by xAbdoAT** [Myinx/Undawn-Macro-Piano-All-Songs-#1]
same issue G1 F1 not working and some notes wrong is it possible to fix it ?

**Comment by xcoldbeautyx** [comment]
> same issue G1 F1 not working and some notes wrong is it possible to fix it ?

I had F1 turned off when playing because it was way too loud, making it difficult to hear other keys like F2 and F3.

Regarding the incorrect notes, try using a different MIDI and see if it exhibits a similar problem.

**Comment by xDevGuru** [comment]
okay bro ill try thanks
